config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:"tops#index"

  resources :incomes
  resources :fixedcosts
  resources :variables
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fixedcost.rb
class Fixedcost < ApplicationRecord
end

app/models/income.rb
class Income < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :incomes
end

app/models/variable.rb
class Variable < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/fixedcosts_controller.rb
class FixedcostsController < ApplicationController
  before_action :set_fixedcost, except: [:index, :new, :create]

  def index
    @fixeds = Fixedcost.order(created_at: :asc)
  end

  def new
    @fixed = Fixedcost.new
  end

  def create
    @fixed = Fixedcost.new(fixedcost_params)
    if @fixed.save
      redirect_to @fixed, notice: '項目を登録しました'
    else
      redirect_to action: :new
    end
  end

  def show
    
  end

  def edit
    
  end

  def update
    if @fixed.update(fixedcost_params)
      redirect_to @fixed, notice: '項目を編集しました'
    else
      redirect_to action: :new
    end
  end

  def destroy
    @fixed.destroy
    redirect_to @fixed, notice: '項目を削除しました'
  end

  private

  def fixedcost_params
    params.require(:fixedcost).permit(:name, :discription)
  end

  def set_fixedcost
    @fixed = Fixedcost.find(params[:id])
  end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_income, except: [:index, :new, :create]

  def index
    @incomes = Income.where(user_id:current_user.id).order(created_at: :asc)

  end

  def new
    @income = Income.new
  end

  def create
    binding.pry
    @income = Income.new(income_params)
    if @income.save
      redirect_to @income, notice: '項目を登録しました'
    else
      redirect_to action: :new
    end
  end

  def show

  end

  def edit

  end

  def update
    if @income.update(income_params)
      redirect_to @income, notice: '項目を編集しました'
    else
      redirect_to action: :new
    end
  end

  def destroy
    @income.destroy
    redirect_to @income, notice: '項目を削除しました'
  end

  private
  def income_params
    binding.pry
    params.require(:income).permit(:name, :discription,:amount,:year_month).merge(user_id: current_user.id)
  end

  # def year_params
  #   params.permit(:year_month)
  # end

  def set_income
    @income = Income.find(params[:id])
  end

end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
    
  end
end

app/controllers/variables_controller.rb
class VariablesController < ApplicationController
  before_action :set_variable, except: [:index, :new, :create]

  def index
    @variables = Variable.order(created_at: :asc)
  end

  def new
    @variable = Variable.new
  end

  def create
    @variable = Variable.new(variable_params)
    if @variable.save
      redirect_to @variable, notice: '項目を登録しました'
    else
      redirect_to action: :new
    end
  end

  def show
    
  end

  def edit
    
  end

  def update
    if @variable.update(variable_params)
      redirect_to @variable, notice: '項目を編集しました'
    else
      redirect_to action: :new
    end
  end

  def destroy
    @variable.destroy
    redirect_to @variable, notice: '項目を削除しました'
  end

  private

  def variable_params
    params.require(:variable).permit(:name, :discription)
  end

  def set_variable
    @variable = Variable.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fixedcosts_helper.rb
module FixedcostsHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/variables_helper.rb
module VariablesHelper
end

app/views/fixedcosts/edit.html.haml
.fixedcost-edit
  %h2.fixedcost-edit__title
    固定費項目登録
  .fixedcost-edit__content
  = form_for @fixed do |f|
    = link_to fixedcosts_path, method: :get do
      固定費項目一覧へ
    = render "incomes/form" ,f: f
    = f.submit "edit"

app/views/fixedcosts/index.html.haml
.fixed-index
  %h2.fixed-index__title
    固定費項目一覧
  .fixed-index__link
    =link_to new_fixedcost_path do
      項目登録する
  .new_fixed__content
    -if @fixeds.present?
      %table
        %thead
          %tr
            %th 項目
            %th 備考
        %tbody
          -@fixeds.each do |fixed|
            %tr
              %td
                = fixed.name
              %td
                = fixed.discription
              %td
                = link_to edit_fixedcost_path(fixed.id) do
                  編集
              %td
                = link_to fixedcost_path(fixed.id), method: :delete, data:{confirm: "本当に削除しますか？"} do
                  削除
    -else
      %p.empty
        登録されている項目はありません

app/views/fixedcosts/new.html.haml
.fixedcost-new
  %h2.fixedcost-new__title
    固定費項目登録
  .fixedcost-new__content
  = form_for @fixed do |f|
    = link_to fixedcosts_path, method: :get do
      固定費一覧に戻る
    = render "incomes/form" ,f: f
    = f.submit "fixedcost"

app/views/fixedcosts/show.html.haml
.fixedcost-show
  %h2.fixedcost-show__title
    項目詳細
  .fixedcost-show__link
    = link_to edit_fixedcost_path(@fixed) do
      編集
    = link_to fixedcosts_path, method: :get do
      固定費項目一覧へ
  .fixedcost-show__content
    .fixedcost-show__content--name
      項目名
      = @fixed.name
    .fixedcost-show__content--discription
      説明
      = @fixed.discription

app/views/incomes/_form.html.haml
.item-form__year-month
  = f.label:name, "年月"
  = f.date_field:year_month
.item-form__name
  = f.label:name, "項目名"
  = f.text_field:name
.item-form__amount
  = f.label:name, "金額"
  = f.text_field:amount
.item-form__discription
  = f.label:name, "説明"
  = f.text_field:discription

app/views/incomes/edit.html.haml
.income-edit
  %h2.income-edit__title
    収入項目登録
  .income-edit__content
  = form_for @income do |f|
    = link_to incomes_path, method: :get do
      収入一覧に戻る
    = render "form" ,f: f
    = f.submit "edit"

app/views/incomes/index.html.haml
.income-index
  %h2.income-index__title
    収入項目一覧
  .income-index__link
    -# = form_for new_income_path do |f|
    -#   = f.label:name, "年月"
    -#   = f.month_field:year_month
    -#   = f.submit "登録する"
    =link_to new_income_path do
      項目登録する
  .new_income__content
    -if @incomes.present?
      %table
        %thead
          %tr
            %th 年月
            %th 項目
            %th 金額
            %th 説明
        %tbody
          -@incomes.each do |income|
            %tr
              %td
                =income.year_month
              %td
                = income.name
              %td
                = income.amount
              %td
                = income.discription
              %td
                = link_to edit_income_path(income.id) do
                  編集
              %td
                = link_to income_path(income.id), method: :delete, data:{confirm: "本当に削除しますか？"} do
                  削除
      .new_income__content--sum
        収入合計
        = @incomes.sum(:amount)
        円
    -else
      %p.empty
        登録されている項目はありません

app/views/incomes/new.html.haml
.income-new
  %h2.income-new__title
    収入項目登録
  .income-new__content
  = form_for @income do |f|
    = link_to incomes_path, method: :get do
      収入一覧に戻る
    = render "form" ,f: f
    = f.submit "income"
  
  

app/views/incomes/show.html.haml
.income-show
  %h2.income-show__title
    項目詳細
  .income-show__link
    = link_to edit_income_path(@income) do
      編集
    = link_to incomes_path, method: :get do
      収入項目一覧へ
  .income-show__content
    .income-show__content--name
      年月
      = @income.year_month
    .income-show__content--name
      項目名
      = @income.name
    .income-show__content--amount
      金額
      = @income.amount
    .income-show__content--discription
      説明
      = @income.discription

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Kakeiko
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    -if flash.notice
      = flash.notice
    = yield

app/views/tops/index.html.haml
.top
  .top__header
    %h1.top__header--title
      Kakeiko
    -if user_signed_in?
      = link_to  destroy_user_session_path, method: :delete do
        logout
  .top__main
    .top__main--left
      %h2.top__main--left--title
        項目設定
        .item
          .item__income
            = link_to incomes_path, method: :get, class:"item__income--link" do
              income
          .item__fixedcost
            = link_to fixedcosts_path, method: :get, class:"item__fixedcost--link" do
              fixedcost
          .item__variable
            = link_to variables_path, method: :get, class:"item__variable--link" do
              variablecost
    .top__main--right
      %h2.top__main--right--title

app/views/variables/edit.html.haml
.variable-edit
  %h2.variable-edit__title
    変動費項目登録
  .variable-edit__content
  = form_for @variable do |f|
    = link_to variables_path, method: :get do
      変動費一覧へ
    = render "incomes/form" ,f: f
    = f.submit "edit"

app/views/variables/index.html.haml
.variable-index
  %h2.variable-index__title
    変動費項目一覧
  .variable-index__link
    =link_to new_variable_path do
      項目登録する
  .new_variable__content
    -if @variables.present?
      %table
        %thead
          %tr
            %th 項目
            %th 備考
        %tbody
          -@variables.each do |variable|
            %tr
              %td
                = variable.name
              %td
                = variable.discription
              %td
                = link_to edit_variable_path(variable.id) do
                  編集
              %td
                = link_to variable_path(variable.id), method: :delete, data:{confirm: "本当に削除しますか？"} do
                  削除
    -else
      %p.empty
        登録されている項目はありません

app/views/variables/new.html.haml
.variable-new
  %h2.variable-new__title
    変動費項目登録
  .variable-new__content
  = form_for @variable do |f|
    = link_to variables_path, method: :get do
      変動費一覧へ
    = render "incomes/form" ,f: f
    = f.submit "variablecost"

app/views/variables/show.html.haml
.variable-show
  %h2.variable-show__title
    項目詳細
  .variable-show__link
    = link_to edit_variable_path(@variable) do
      編集
    = link_to variables_path, method: :get do
      変動費項目一覧へ
  .variable-show__content
    .variable-show__content--name
      項目名
      = @variable.name
    .variable-show__content--discription
      説明
      = @variable.discription